version: '3.7'
volumes:
    database:

services:
    db:
        image: mariadb:latest
        container_name: editor-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=editor-service
            - MYSQL_DATABASE=editor-service
            - MYSQL_USER=editor-service
            - MYSQL_PASSWORD=editor-service

    phpMyAdmin:
            image: phpmyadmin/phpmyadmin:latest
            container_name: editor-phpmyadmin
            environment:
                - PMA_ARBITRARY=1
            links:
                - db
            ports:
                - 80:80
            volumes:
                - /sessions

    service:
            build:
                context: .
                dockerfile: Dockerfile.jvm
            depends_on: 
                - "db"
            container_name: editor-service
            image: editor-service
            ports:
                - 8080:8080
            environment:
                quarkus.datasource.jdbc.url: "jdbc:mysql://db:3306/editor-service"

    bot:
        image: guismoreira/editor-bot:latest
        container_name: editor-bot
            
    app:
        container_name: editor-blockly
        build:  
            context: ./app
            dockerfile: Dockerfile
        ports:
            - '7000:7000'